name: model_monitoring_ml_project
on:
  push:
    branches: [ dev_dockerhub ]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container:
      image: rkorivi/ml_project:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        run: |
          # Your ML workflow goes here
          # pip install -r requirements.txt
          python train.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
         
